### ISSUE TITLE
[Website] Typo on the word "builds" on the November 30th 2024 fr blog post

### ISSUE THREAD

**Issue by Chaoliame** [deufrai/als#204]
Can be found here : https://next.als-app.org/fr/blog/0.7/

- Issue on this text : "Préparations des **buils** en cours !"
- Expected text : "Préparations des **builds** en cours !"

**Comment by deufrai** [comment]
Thanks for helping us build a proper website for the v0.7 release :)

**Comment by deufrai** [comment]
Fixed and deployed with https://forge.wardsback.org/als/als-website/-/pipelines/273
