### ISSUE TITLE
Installation on Ubuntu 24.04

### ISSUE THREAD

**Issue by WirthmU** [deufrai/als#206]
I am installing the directions here and get the following error:

```
(venv) iot-flt2@iot-flt2:/iot-flt2$ python setup.py develop
/iot-flt2/setup.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import VersionConflict, require
Compiling UI files
==================

Compiling RC files
==================
Executing command : pyrcc5 /iot-flt2/src/resources/resource.qrc -o /iot-flt2/src/generated/resource_rc.py
Traceback (most recent call last):
  File "/iot-flt2/setup.py", line 25, in <module>
    compile_ui_and_rc.main()
  File "/iot-flt2/utils/compile_ui_and_rc.py", line 31, in main
    completed_process = subprocess.run([command, ] + args.split(" "))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyrcc5'
```

any help to this?

**Comment by deufrai** [comment]
Hi

First of all, congratulations for making it that far in the process, especially on such a recent distro.

A bit of context : We are currently finalizing (after 7 beta releases) the v0.7 of ALS, along with a new website and complete documentation. Both still very W.I.P.
 
And if you'd like to, you'll be a perfect guinea pig for testing our packages & installation instructions.
You can download a ready-to-use ALS package for your system from the new (WIP, again) site https://next.als-app.org

Once you click the appropriate download buton, a new browser tab will open on the "installation" instructions.
This latest beta-7 includes a utility that creates an ALS launcher in your system menu. After your first launch, check out the "Utilities" menu :)

And pretty please, report how it went. I know we may still have a few edge cases to sort out on some distros

Hoping for the best and truly yours...

**Comment by deufrai** [comment]
Reading you terminal, I can see perms issues on the preparation of files in your 'work' folder.
I's like to hear more about that as well and will be glad to assist

**Comment by deufrai** [comment]
I see : you created the scan & work folder, in your own user subtree, but used `sudo`. So those folders are owned by `root`

Hence ALS failing to write into your `work`because it runs as yourself ;)

**Comment by WirthmU** [comment]
I have changed ownership of the two folders to iot-flt2 - thank you for your tip.

The system I have installed is a headless fit2-PC.

This is the system information:

![image](https://github.com/user-attachments/assets/6db64c41-56ce-4ac3-aef6-d789968b9c4b)

**Comment by deufrai** [comment]
Many thanks for the details.
Setup issue resolved.
May ALS treat you well and help you

Clear skies !
